test changes
serhiichuk/sokolia pull request #1
Opened 2023-08-29 10:28 UTC by Saniou

Styling Branch

2023-08-29 11:45 UTC, serhiichuk requested changes

2023-08-29 11:45 UTC, serhiichuk commented on package.json
> +    "postcss-cli": "^10.1.0",
а для чого ця тулза нам?

2023-08-29 11:45 UTC, serhiichuk commented on package-lock.json
схоже що ти поставив залежність не чарез `pnpm`, а за допомогою `npm`. Так не повинно бути, для установки залежностей юзай такий спосіб `pnpm add postcss --filter @sokolia/playground`

2023-08-29 11:45 UTC, serhiichuk commented on package-lock.json
https://pnpm.io/filtering

2023-08-29 13:08 UTC, Saniou commented on package-lock.json
Оце вже лютий фейл

2023-08-29 13:09 UTC, Saniou commented on package.json
> +    "postcss-cli": "^10.1.0",
Цю штуку я не ставив можливо з npm підгрузилось?

2023-08-29 13:17 UTC, Saniou commented on package-lock.json
Стоп хоча ні я не згоден
Я йшов чітко за інструкцією і там якраз я написав pnpm бо у я випадково хотів поставити:
npm install react-icons --save
І ця команда у мене просто не запрацювала
Але при цьому проект у мене працює

2023-08-30 11:29 UTC, serhiichuk commented on package-lock.json
хм, дивно. в мене все чітко ставиться
```bash
➜  sokolia git:(master) rm -rf ./**/node_modules   
➜  sokolia git:(master) pnpm install                                        
Scope: all 8 workspace projects
Lockfile is up to date, resolution step is skipped
Packages: +699
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Packages are hard linked from the content-addressable store to the virtual store.
  Content-addressable store is at: /Users/tarasserhiichuk/Library/pnpm/store/v3
  Virtual store is at:             node_modules/.pnpm
node_modules/.pnpm/dtrace-provider@0.8.8/node_modules/dtrace-provider: Running install script, done in 6.6s
node_modules/.pnpm/core-js@3.27.1/node_modules/core-js: Running postinstall script, done in 52ms
node_modules/.pnpm/spawn-sync@1.0.15/node_modules/spawn-sync: Running postinstall script, done in 44ms
Progress: resolved 699, reused 697, downloaded 0, added 699, done
node_modules/.pnpm/esbuild@0.16.17/node_modules/esbuild: Running postinstall script, done in 366ms

devDependencies:
+ @types/node 18.15.3
+ @typescript-eslint/eslint-plugin 5.56.0
+ @typescript-eslint/parser 5.56.0
+ eslint 8.36.0
+ typescript 5.0.2

The integrity of 3269 files was checked. This might have caused installation to take longer.
Done in 13.2s
➜  sokolia git:(master) git status                     
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
```

2023-08-30 11:30 UTC, serhiichuk commented on package.json
> +    "postcss-cli": "^10.1.0",
якщо ти ставив залежності чере npm, то може тому це і зявилось. треба юзати pnpm

2023-09-05 08:00 UTC, closed without merging