New branch markdown and editor
serhiichuk/sokolia pull request #2
Opened 2023-09-04 12:04 UTC by Saniou

2023-09-05 10:59 UTC, serhiichuk commented on packages/ui/src/notes-popup/NoteContentEditor.tsx
> +  // };
таке не варто залишати, це сміттєвий код

2023-09-05 10:59 UTC, serhiichuk commented on packages/ui/src/notes-popup/NoteContentEditor.tsx
> +      /> */}
це також вже непотрібно

2023-09-05 11:26 UTC, serhiichuk requested changes

2023-09-05 11:26 UTC, serhiichuk commented on packages/ui/src/notes-popup/NoteContentView.tsx
> +	<span >{props.content}</span>
лишній пробіл же

2023-09-05 11:26 UTC, serhiichuk commented on packages/ui/src/notes-popup/NoteListItem.tsx
> +        {(props.note.updatedAt && <span>Updated {format(props.note.updatedAt, 'dd MMM')}</span>)}
я знаю що це так було, але так не дуже правильно, я маю на увазі - коли багато логіки в темплейтах, краще ці данні в якусь змінну виносити, це простіше читати, і легко покривати тестами (якби такі були)

2023-09-05 11:34 UTC, Saniou commented on packages/ui/src/notes-popup/NoteContentView.tsx
> +	<span >{props.content}</span>
Я там оновив трохи код, потім заціниш

2023-09-10 19:03 UTC, serhiichuk commented
в цілому все ок. я поклікав, бачу що працює (окрім збереження картинки, але то окремо зробим), є питання по дизайну, але краще пізніше просто дати на тестування Олі чи Іллі, і отримати разом правки.

в подальшому, я додам eslint та ts check в СІ, бо бачу помилки.
також, кожен наступний PR має в собі містити опис в якому буде детально описано що там буде зроблено (рекомендую складати собі цей список перед тим як взявся за роботу)

2023-09-10 19:03 UTC, serhiichuk approved these changes

2023-09-10 19:03 UTC, serhiichuk commented on packages/ui/src/notes-popup/NoteContentEditor.tsx
> +import ReactMarkdown from 'react-markdown'
ці імпорти не використовуються, краще їх видалити

2023-09-10 19:03 UTC, serhiichuk commented on packages/ui/src/notes-popup/NoteContentEditor.tsx
>  import classes from './NoteContentEditor.module.pcss'
ці імпорти не використовуються, краще їх видалити

2023-09-10 19:03 UTC, serhiichuk commented on packages/ui/src/notes-popup/NoteContentView.tsx
> +	<span >{props.content}</span>
норм, декомпозиція - це добре. в нас на фронті прийнято розділяти UI комроненти на три типи:
1. Тупі - ті що не знають про зовнішній світ нічого, вони тупо рендерять щось, всі необхідні данні передають пропсами
2. Розумні - ті що знають про те як влаштований проект, знають про те звідни взяти данні і т.д. В той самий час, вони юзають тупі для рендеру
3. Контроллери - це "вхідні точки" на сторінку, їх завдання насетапати все для роботи сторінки, зазвичай юзають розумні компоненти

Пропоную, в подальшому +- дотримуватись цього концепту, це дозволяє дуже зменшувати связаність

2023-09-10 19:06 UTC, merged