mark-done
serhiichuk/sokolia pull request #3
Opened 2023-09-13 10:44 UTC by Saniou

1. Edit screen when creating a new note
2. media elements support
3. styling the rest element

2023-09-13 20:38 UTC, serhiichuk commented
схоже що ти не підмержив собі мастер

2023-09-13 20:52 UTC, serhiichuk commented on packages/ui/src/notes-popup/NoteListItem.tsx
> +    localStorage.setItem(`buttonActive_${props.note.id}`, JSON.stringify(active));
я не зовсім розумію навіщо ці сети в сторадж, тут треба просто оновити статус сутності на done, реакт має слідкувати за списком данних і сам рендеритись

от тут https://github.com/serhiichuk/sokolia/blob/master/packages/ui/src/notes-popup/NoteListItem.tsx#L21-L23 є колбеки, за допомогою яких можна змінювати сутність.

Короче кажучи, все починаєтсья з доменного шару https://github.com/serhiichuk/sokolia/blob/master/packages/domain/src/note/NoteEntity.ts
Там точка істини, і замість отих setActive, setDone, потрібно правильно оновлювати сутність

2023-09-13 20:52 UTC, serhiichuk commented on packages/ui/src/notes-popup/NoteListItem.tsx
> +    localStorage.setItem(`buttonActive_${props.note.id}`, JSON.stringify(active));
ось [тут ](https://github.com/serhiichuk/sokolia/blob/master/apps/playground/src/pages/Home.tsx#L10-L47) видно як дістаються і сінкаються данні

2023-09-13 20:52 UTC, serhiichuk commented on packages/ui/src/notes-popup/NoteContentEditor.tsx
> -import ReactMarkdown from 'react-markdown'
це вже виправлено в мастері =)

2023-09-13 20:52 UTC, serhiichuk commented on packages/ui/src/notes-popup/NotesPopup.tsx
> +	const [isCreatingNote, setIsCreatingNote] = useState(false);
тип потрібно вказувати

2023-09-13 20:52 UTC, serhiichuk commented on packages/ui/src/notes-popup/NotesPopup.tsx
> +					notes={isCreatingNote ? [...notes] : notes}
а це що за магія?

2023-09-14 05:46 UTC, Saniou commented on packages/ui/src/notes-popup/NoteListItem.tsx
> +    localStorage.setItem(`buttonActive_${props.note.id}`, JSON.stringify(active));
Це виходить що при натисканні на кнопку  'Mark as Done'
Ось цей масив повинен змінюватись?
0 : 
{id: 1, title: "test", content: "<p>test</p>", status: "draft", createdAt: 1694616551650}
content: "<p>test</p>"
createdAt : 1694616551650
id : 1
status : "draft"
title: "test"
І замість статуса draft повинен бути статус done?

2023-09-14 05:48 UTC, Saniou commented on packages/ui/src/notes-popup/NotesPopup.tsx
> +					notes={isCreatingNote ? [...notes] : notes}
я не автор цього заклинання але воно працює))

2023-09-15 17:53 UTC, serhiichuk commented on packages/ui/src/notes-popup/NoteListItem.tsx
> +    localStorage.setItem(`buttonActive_${props.note.id}`, JSON.stringify(active));
саме так 
П.С.: повідомленя в гітхабі підтримують markdown форматування, коли код вставляєш то краще завертай в code-block

2023-09-18 13:49 UTC, serhiichuk requested changes

2023-09-18 13:49 UTC, serhiichuk commented on packages/ui/src/notes-popup/NotesPopup.tsx
> +					notes={isCreatingNote ? [...notes] : notes}
не знаю де ти то взяв, але пулл реквест твій, тож ти і відповідай за магію.
копіпастити щось з інтернетів не розібравшись - дуже погана практика. А працюючи 
компанії, аргументи типу "це я в інтернеті побачив, я хз чому воно не працює" явно працюють проти тебе.

стосовно цього кейсу - тут ти використав оператор sperad, який руйнує ссилку на оригінальний масив (якщо не вкурсі про що це - [читай](https://ui.dev/primitive-vs-reference-values-in-javascript). Якщо щось не працювало з ссилкою на оригінальний масив, то певно "хтось" мутує данні напряму, а не через репозиторій, або щось в тому дусі

2023-09-18 13:49 UTC, serhiichuk commented on packages/ui/src/notes-popup/NoteListItem.tsx
> +			setTimeLeft(formatDistanceToNow(newNote.expiredAt as number));
newNote.expiredAt - тут може бути undefined, тоді незрозуміло як себе поведе ф-ція formatDistanceToNow з undefined.

я думаю, що якщо відсутній expiredAt то нічого сети не потрібно

2023-09-18 13:49 UTC, serhiichuk commented on packages/ui/src/notes-popup/NoteListItem.tsx
> +	const [isMarkedDone, setIsMarkedDone] = useState<boolean>(false);
а чому initial value не з статсуса нотатки берем?
тут взагалі напрошується get/set поверх сутності. напр. якось так:
```
const isNoteStatusDone = () => props.note.status === 'done';
const setNoteAsDone = (node) => onUpdateNote({ ...note, status: 'done' })
```

2023-09-18 13:49 UTC, serhiichuk commented on packages/ui/src/notes-popup/NoteListItem.tsx
> +	const changeBackground = async () => {
а про який background іде мова?
наскільки я знаю, в поточному ф-налі ніяких фонів не змінюємо.

якщо це зміна фону через зміну статусу, то краще використати неймінг onClickDone

p.s.: для ф-цій обробників кліків, чи івентів краще юзати неймінг onActionSomething

2023-09-18 13:49 UTC, serhiichuk commented on packages/ui/src/notes-popup/NoteListItem.tsx
> +		<div style={{ backgroundColor: isMarkedDone ? "done" : '' }} className={`${classes.wrapper} ${statusClassName()}`}>
а що це за колір такий "done"?

2023-09-18 13:49 UTC, serhiichuk commented on packages/ui/src/notes-popup/NotesPopup.tsx
> +					notes={isCreatingNote ? [...notes] : notes}
так а з цим що будем робити?

2023-09-19 12:21 UTC, Saniou commented on packages/ui/src/notes-popup/NoteListItem.tsx
> +	const [isMarkedDone, setIsMarkedDone] = useState<boolean>(false);
Твоєю підказкою я вирішив одразу 2 прблеми)))

2023-09-19 12:23 UTC, Saniou commented on packages/ui/src/notes-popup/NotesPopup.tsx
> +					notes={isCreatingNote ? [...notes] : notes}
Прибрати. 
Я поняв, що воно тут лишнє, але це робочий варіант зі спредом

2023-09-19 12:24 UTC, Saniou commented on packages/ui/src/notes-popup/NoteListItem.tsx
> +		<div style={{ backgroundColor: isMarkedDone ? "done" : '' }} className={`${classes.wrapper} ${statusClassName()}`}>
Я типу ссилався на statusClassName, але це лишнє бо ця функція уже була викликана

2023-09-19 18:36 UTC, serhiichuk commented on packages/ui/src/notes-popup/NoteListItem.tsx
> +			setIsMarkedDone(false);
при виклику цієї ф-ції, буде оновлено тільки стейт компоненту, а потрібно оновлювати сутність.
сприймай репозиторій і сутності в них як глобальний стор

2023-09-20 14:31 UTC, Saniou commented on packages/ui/src/notes-popup/NoteListItem.tsx
> +			setIsMarkedDone(false);
Ось тут не дуже зрозумів

2023-09-20 20:49 UTC, serhiichuk commented on packages/ui/src/notes-popup/NoteListItem.tsx
> +			setIsMarkedDone(false);
ти створив локальний стейт `isMarkedDone, setIsMarkedDone` і змінюєш його по кліку, але вордочас, ти викликаєш колбеки onUpdateNone з новим статусом (а статус === "done" це і є isMarkedDone). 
Тобто, ви створюєш дві точки істини, одна - це локальний стейт, інша це props.note.status.
Набагато краще, і простіше, коли в тебе є одне джерело істини, особливо враховуючи, що при виклику onUpdateNone оновлюється props.note, і компонент просто перерендерюється.

Спробуй просто всюди видалити setIsMarkedDone, все ж буде так само працювати

2023-09-26 08:43 UTC, serhiichuk approved these changes

2023-09-26 08:44 UTC, merged